Repository anarolon/person-and-ghost, pull requests merged in 2021-12, with the labels that each got.

#190 DES #157 | Room 2-1 Design
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/.DS_Store
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_!.anim
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_!.anim.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim.anim
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim.anim.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim_2.anim
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim_2.anim.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim_3.anim
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim_3.anim.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim_4.anim
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/Fire_Anim_4.anim.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_light1_0.controller
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_light1_0.controller.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_light2_0.controller
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_light2_0.controller.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_light4_0.controller
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_light4_0.controller.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_lights_15.controller
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/anim_lights_15.controller.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/env_objects.png.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/env_objects_far.png.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/environment.png.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/ground.png.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/walls.png.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/Sliced/wood_env.png.meta
  Assets/Imports/Environment/Pixel2DCastleTileset/Sprites/walls.png.meta
  Assets/Resources/Prefabs/Ghost.prefab
  Assets/Resources/Prefabs/LostSpirit.prefab
  Assets/Resources/Prefabs/Person.prefab
  Assets/Resources/Prefabs/RogueSpirit.prefab
  Assets/Resources/Sprites/Pixel2DCastleTileset_ModifiedSprites/room1-1_ground.png.meta
  Assets/Scenes/Room 2-1.unity
  ProjectSettings/TagManager.asset
Labels: development, design

#189 BUG #188 | Fix Issues
  Assets/Resources/Prefabs/GameUI.prefab
  Assets/Resources/Prefabs/Goal.prefab
  Assets/Scenes/Room 1-1.unity
  Assets/Scenes/Room 1-2.unity
  Assets/Scenes/Room 1-3.unity
  Assets/Scenes/Room 2-2.unity
  Assets/Scenes/Room 2-3.unity
  Assets/Scripts/ContactKiller.cs
  Assets/Scripts/GameManagerController.cs
  Assets/Scripts/Goal.cs
  Assets/Scripts/Utils/Utility.cs
Labels: bug, development

#194 Des#192
  Assets/Resources/Prefabs/Collectable.prefab
  Assets/Resources/Prefabs/GameUI.prefab
  Assets/Resources/Prefabs/PressurePlateDoor_Hatch.prefab
  Assets/Resources/Prefabs/PressurePlateDoor_Normal.prefab
  Assets/Scenes/Room 1-2.unity
  Assets/Scenes/Room 1-3.unity
  Assets/Scenes/Room 2-1.unity
Labels: design, art
