Repository anarolon/person-and-ghost, pull requests merged in 2021-11, with the labels that each got.

#150 Dev#102
  Assets/Resources/Prefabs/Ghost.prefab
  Assets/Scripts/Ghost/GhostAnchor.cs
  Assets/Scripts/Ghost/GhostPossession.cs
  Assets/Tests/PlayMode/GhostTests/GhostPossessionTests.cs
Labels: development, feature

#149 Dev#99
  Assets/Resources/Actions/Controller.inputactions
  Assets/Resources/Prefabs/GameManager.prefab
  Assets/Resources/Prefabs/User Interface.prefab
  Assets/Resources/Prefabs/User Interface.prefab.meta
  Assets/Scenes/Room 1-1.unity
  Assets/Scenes/Room 1-2.unity
  Assets/Scenes/Room 1-3.unity
  Assets/Scenes/Room 2-1.unity
  Assets/Scenes/Room 2-2.unity
  Assets/Scenes/Room 2-3.unity
  Assets/Scripts/GameManagerController.cs
  Assets/Scripts/PauseMenuController.cs
  Assets/Scripts/PauseMenuController.cs.meta
  Assets/Scripts/Utils/Actions.cs
  Assets/Scripts/Utils/Utility.cs
  Assets/Tests/PlayMode/PauseMenuTests.cs
  Assets/Tests/PlayMode/PauseMenuTests.cs.meta
  UserSettings/EditorUserSettings.asset
Labels: development, feature

#162 Update DEV #154 Environmental 1-1 Branch
  Assets/Resources/Actions/Controller.inputactions
  Assets/Resources/Prefabs/BigBoy.prefab
  Assets/Resources/Prefabs/Bird (Clawed).prefab
  Assets/Resources/Prefabs/Bird.prefab
  Assets/Resources/Prefabs/BuffBoy.prefab
  Assets/Resources/Prefabs/Crate.prefab
  Assets/Resources/Prefabs/FrogWizard.prefab
  Assets/Resources/Prefabs/GameManager.prefab
  Assets/Resources/Prefabs/Ghost.prefab
  Assets/Resources/Prefabs/LostSpirit.prefab
  Assets/Resources/Prefabs/Person.prefab
  Assets/Resources/Prefabs/RogueSpirit.prefab
  Assets/Resources/Prefabs/User Interface.prefab
  Assets/Resources/Prefabs/User Interface.prefab.meta
  Assets/Resources/Sprites/Bad Spirit.PNG
  Assets/Resources/Sprites/Bad Spirit.PNG.meta
  Assets/Resources/Sprites/BigBoy.png
  Assets/Resources/Sprites/BigBoy.png.meta
  Assets/Resources/Sprites/BuffBoy.png
  Assets/Resources/Sprites/BuffBoy.png.meta
  Assets/Resources/Sprites/FrogEnemy Idle-Sheet.png
  Assets/Resources/Sprites/FrogEnemy Idle-Sheet.png.meta
  Assets/Resources/Sprites/Mad Spirit.PNG
  Assets/Resources/Sprites/Mad Spirit.PNG.meta
  Assets/Resources/Sprites/Sad Spirit.PNG
  Assets/Resources/Sprites/Sad Spirit.PNG.meta
  Assets/Resources/Sprites/bird.png
  Assets/Resources/Sprites/bird.png.meta
  Assets/Scenes/PlayGround.unity
  Assets/Scenes/Room 1-1.unity
  Assets/Scenes/Room 1-2.unity
  Assets/Scenes/Room 1-3.unity
  Assets/Scenes/Room 2-1.unity
  Assets/Scenes/Room 2-2.unity
  Assets/Scenes/Room 2-3.unity
  Assets/Scripts/GameManagerController.cs
  Assets/Scripts/PauseMenuController.cs
  Assets/Scripts/PauseMenuController.cs.meta
  Assets/Scripts/Utils/Actions.cs
  Assets/Scripts/Utils/Utility.cs
  Assets/Tests/PlayMode/PauseMenuTests.cs
  Assets/Tests/PlayMode/PauseMenuTests.cs.meta
  Assets/Tests/PlayMode/StolenActionTests/BigBoyTests.cs
  Assets/Tests/PlayMode/StolenActionTests/BigBoyTests.cs.meta
  Assets/Tests/PlayMode/StolenActionTests/BuffBoyTests.cs
  UserSettings/EditorUserSettings.asset
Labels: development

#173 Dev#161 | Incorporate Person Animations into Person Prefab
  Assets/Resources/Prefabs/Person.prefab
  Assets/Resources/Sprites/Person Sprites.meta
  Assets/Resources/Sprites/Person Sprites/Animations.meta
  Assets/Resources/Sprites/Person Sprites/Animations/PersonAnimator.controller
  Assets/Resources/Sprites/Person Sprites/Animations/PersonAnimator.controller.meta
  Assets/Resources/Sprites/Person Sprites/Animations/cling.anim
  Assets/Resources/Sprites/Person Sprites/Animations/cling.anim.meta
  Assets/Resources/Sprites/Person Sprites/Animations/death.anim
  Assets/Resources/Sprites/Person Sprites/Animations/death.anim.meta
  Assets/Resources/Sprites/Person Sprites/Animations/falling.anim
  Assets/Resources/Sprites/Person Sprites/Animations/falling.anim.meta
  Assets/Resources/Sprites/Person Sprites/Animations/idle.anim
  Assets/Resources/Sprites/Person Sprites/Animations/idle.anim.meta
  Assets/Resources/Sprites/Person Sprites/Animations/jumping.anim
  Assets/Resources/Sprites/Person Sprites/Animations/jumping.anim.meta
  Assets/Resources/Sprites/Person Sprites/Animations/meditate.anim
  Assets/Resources/Sprites/Person Sprites/Animations/meditate.anim.meta
  Assets/Resources/Sprites/Person Sprites/Animations/moving.anim
  Assets/Resources/Sprites/Person Sprites/Animations/moving.anim.meta
  Assets/Resources/Sprites/Person Sprites/Animations/win.anim
  Assets/Resources/Sprites/Person Sprites/Animations/win.anim.meta
  Assets/Resources/Sprites/Person Sprites/PersonAnimationController.cs
  Assets/Resources/Sprites/Person Sprites/PersonAnimationController.cs.meta
  Assets/Resources/Sprites/Person Sprites/person_cling.png
  Assets/Resources/Sprites/Person Sprites/person_cling.png.meta
  Assets/Resources/Sprites/Person Sprites/person_death.png
  Assets/Resources/Sprites/Person Sprites/person_death.png.meta
  Assets/Resources/Sprites/Person Sprites/person_falling.png
  Assets/Resources/Sprites/Person Sprites/person_falling.png.meta
  Assets/Resources/Sprites/Person Sprites/person_idle.png
  Assets/Resources/Sprites/Person Sprites/person_idle.png.meta
  Assets/Resources/Sprites/Person Sprites/person_jumping.png
  Assets/Resources/Sprites/Person Sprites/person_jumping.png.meta
  Assets/Resources/Sprites/Person Sprites/person_meditate.png
  Assets/Resources/Sprites/Person Sprites/person_meditate.png.meta
  Assets/Resources/Sprites/Person Sprites/person_moving.png
  Assets/Resources/Sprites/Person Sprites/person_moving.png.meta
  Assets/Resources/Sprites/Person Sprites/person_win.png
  Assets/Resources/Sprites/Person Sprites/person_win.png.meta
  Assets/Scripts/ContactKiller.cs
  Assets/Scripts/Goal.cs
  Assets/Scripts/Person/PersonMovement.cs
  Assets/Scripts/Person/States/CarriedState.cs
  Assets/Scripts/Person/States/ClingState.cs
  Assets/Scripts/Person/States/FallingState.cs
  Assets/Scripts/Person/States/GrappleAimState.cs
  Assets/Scripts/Person/States/IdleState.cs
  Assets/Scripts/Person/States/JumpingState.cs
  Assets/Scripts/Person/States/MeditatingState.cs
  Assets/Scripts/Person/States/MovementState.cs
  Assets/Scripts/Person/States/State.cs
Labels: development, feature, art, animation

#175 ART #141 | Added Ghost Win Animation
  Assets/Resources/Prefabs/Ghost.prefab
  Assets/Resources/Sprites/Ghost Sprites/Animations/Ghost Animator.controller
  Assets/Resources/Sprites/Ghost Sprites/Animations/Ghost Win.anim
  Assets/Resources/Sprites/Ghost Sprites/Animations/Ghost Win.anim.meta
  Assets/Resources/Sprites/Ghost Sprites/Ghost Victory-Sheet.png
  Assets/Resources/Sprites/Ghost Sprites/Ghost Victory-Sheet.png.meta
  Assets/Resources/Sprites/Ghost Sprites/GhostAnimationController.cs
  Assets/Scripts/GameManagerController.cs
  Assets/Scripts/Ghost/GhostPossession.cs
Labels: art, animation

#176 ART #146 | Make Ghostly Invasion Animations
  Assets/Resources/Prefabs/LostSpirit.prefab
  Assets/Resources/Prefabs/RogueSpirit.prefab
  Assets/Resources/Sprites/Spirits Sprites/Animations.meta
  Assets/Resources/Sprites/Spirits Sprites/Animations/badspirit_controller.controller
  Assets/Resources/Sprites/Spirits Sprites/Animations/badspirit_controller.controller.meta
  Assets/Resources/Sprites/Spirits Sprites/Animations/badspirit_moving.anim
  Assets/Resources/Sprites/Spirits Sprites/Animations/badspirit_moving.anim.meta
  Assets/Resources/Sprites/Spirits Sprites/Animations/madspirit_controller.controller
  Assets/Resources/Sprites/Spirits Sprites/Animations/madspirit_controller.controller.meta
  Assets/Resources/Sprites/Spirits Sprites/Animations/madspirit_moving.anim
  Assets/Resources/Sprites/Spirits Sprites/Animations/madspirit_moving.anim.meta
  Assets/Resources/Sprites/Spirits Sprites/Animations/sadspirit_controller.controller
  Assets/Resources/Sprites/Spirits Sprites/Animations/sadspirit_controller.controller.meta
  Assets/Resources/Sprites/Spirits Sprites/Animations/sadspirit_moving.anim
  Assets/Resources/Sprites/Spirits Sprites/Animations/sadspirit_moving.anim.meta
  Assets/Resources/Sprites/Spirits Sprites/badspirit_moving.png
  Assets/Resources/Sprites/Spirits Sprites/badspirit_moving.png.meta
  Assets/Resources/Sprites/Spirits Sprites/madspirit_moving.png
  Assets/Resources/Sprites/Spirits Sprites/madspirit_moving.png.meta
  Assets/Resources/Sprites/Spirits Sprites/sadspirit_moving.png
  Assets/Resources/Sprites/Spirits Sprites/sadspirit_moving.png.meta
Labels: development, art, animation

#174 UI#166 Added Stolen Action Icon and Tool Icon Funcitonality to the UI
  Assets/Resources/Prefabs/Collectable.prefab
  Assets/Resources/Prefabs/GameManager.prefab
  Assets/Resources/Prefabs/GameUI.prefab
  Assets/Resources/Prefabs/Grappling Hook.prefab
  Assets/Resources/Sprites/Grappling_Hook.png
  Assets/Resources/Sprites/Grappling_Hook.png.meta
  Assets/Resources/Sprites/UI Sprites.meta
  Assets/Resources/Sprites/UI Sprites/Big_Boy_Icon.png
  Assets/Resources/Sprites/UI Sprites/Big_Boy_Icon.png.meta
  Assets/Resources/Sprites/UI Sprites/Bird_Icon.png
  Assets/Resources/Sprites/UI Sprites/Bird_Icon.png.meta
  Assets/Resources/Sprites/UI Sprites/Buff_Boy_Icon.png
  Assets/Resources/Sprites/UI Sprites/Buff_Boy_Icon.png.meta
  Assets/Resources/Sprites/UI Sprites/Climbing_Gauntlet_Icon.png
  Assets/Resources/Sprites/UI Sprites/Climbing_Gauntlet_Icon.png.meta
  Assets/Resources/Sprites/UI Sprites/Collectible.png
  Assets/Resources/Sprites/UI Sprites/Collectible.png.meta
  Assets/Resources/Sprites/UI Sprites/Frog_Icon_64x64.png
  Assets/Resources/Sprites/UI Sprites/Frog_Icon_64x64.png.meta
  Assets/Resources/Sprites/UI Sprites/Grappling_Hook_Icon.png
  Assets/Resources/Sprites/UI Sprites/Grappling_Hook_Icon.png.meta
  Assets/Resources/Sprites/empty sprite.png
  Assets/Resources/Sprites/empty sprite.png.meta
  Assets/Scenes/PlayGround.unity
  Assets/Scenes/Room 1-1.unity
  Assets/Scenes/Room 1-2.unity
  Assets/Scenes/Room 1-3.unity
  Assets/Scenes/Room 2-1.unity
  Assets/Scenes/Room 2-2.unity
  Assets/Scenes/Room 2-3.unity
  Assets/Scripts/GameManagerController.cs
  Assets/Scripts/Ghost/GhostAnchor.cs
  Assets/Scripts/Ghost/GhostMovement.cs
  Assets/Scripts/Ghost/GhostPossession.cs
  Assets/Scripts/Tools/ClimbingGauntlet.cs
  Assets/Scripts/Tools/GrapplingHook.cs
  Assets/Scripts/Tools/PersonToolController.cs
  Assets/Scripts/Tools/Tool.cs
  Assets/Scripts/Utils/Actions.cs
  UserSettings/EditorUserSettings.asset
Labels: development, art

#177 Des#156 Deployed Room 1-3 assets
  Assets/Resources/Sprites/Pixel2DCastleTileset_ModifiedSprites/room1-1_pillar.png.meta
  Assets/Scenes/Room 1-3.unity
Labels: design, art

#180 DEV #179 | Update Enemy Prefabs
  Assets/Resources/Prefabs/BigBoy.prefab
  Assets/Resources/Prefabs/Bird (Clawed).prefab
  Assets/Resources/Prefabs/Bird.prefab
  Assets/Resources/Prefabs/BuffBoy.prefab
  Assets/Resources/Prefabs/FrogWizard.prefab
Labels: animation

#181 DES #155 | Added environment sprites to Room 1-2
  Assets/Resources/Sprites/Pixel2DCastleTileset_ModifiedSprites/room1-1_ground.png.meta
  Assets/Scenes/Room 1-2.unity
Labels: design, art

#184 Dev#44 | Create Home Screen
  Assets/HomeSceneController.cs
  Assets/HomeSceneController.cs.meta
  Assets/Resources/Prefabs/GameUI.prefab
  Assets/Scenes/Home Screen.unity
  Assets/Scenes/Home Screen.unity.meta
  Assets/Scripts/PauseMenuController.cs
  Assets/Tests/PlayMode/RoomManagerTests.cs
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: development
